# Generated by Django 5.1.4 on 2024-12-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
