# Generated by Django 5.1.4 on 2025-01-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_text',
        ),
    ]
